
- name: Debug nvim 
  debug: "nvim_home_dir={{ nvim_home_dir }}"

- name: Install vim-plug
  command: 
    command: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    condition: ls ~/.local/share/nvim/site/autoload/plug.vim
    condition_code: 1



- name: Install nvim
  copy:
    src: files/nvim
    dest: "{{ nvim_home_dir }}"

