- name: Install pyenv
  command:
    command: brew install pyenv
    condition: pyenv --version
    condition_code: 1

- name: Install python packages
  command: pip install -r "{{ configdir }}/requirements/python.txt"
  when: python_install
