- name: Install pyenv
  command:
    command: brew install pyenv
    condition: which pyenv
    condition_code: 1

- name: Install poetry
  command:
    command: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    condition: which poetry
    condition_code: 1

- name: Install python packages
  command: pip install -r "{{ configdir }}/requirements/python.txt"
  when: python_install
