require("lazy").setup({
  { "folke/tokyonight.nvim", lazy = false, priority = 1000 },
  { "nvim-telescope/telescope.nvim", dependencies = { "nvim-lua/plenary.nvim" }, cmd = "Telescope", keys = {
    { "<leader>ff", "<cmd>Telescope find_files<cr>", desc = "Find files" },
    { "<leader>fg", "<cmd>Telescope live_grep<cr>", desc = "Live grep" },
    { "<leader>fb", "<cmd>Telescope buffers<cr>", desc = "Find buffers" },
    { "<leader>fh", "<cmd>Telescope help_tags<cr>", desc = "Help tags" },
    { "<leader>gc", "<cmd>Telescope git_commits<cr>", desc = "Git commits" },
    { "<leader>gs", "<cmd>Telescope git_status<cr>", desc = "Git status" },
  }},
  { "nvim-tree/nvim-tree.lua", cmd = { "NvimTreeToggle", "NvimTreeFocus" }, keys = { { "<leader>e", "<cmd>NvimTreeToggle<cr>", desc = "Toggle tree" } }, opts = { view = { width = 35 }, git = { ignore = false } } },
  { "lewis6991/gitsigns.nvim", event = { "BufReadPre", "BufNewFile" }, opts = { signs = { add = { text = "▎" }, change = { text = "▎" }, delete = { text = "" }, topdelete = { text = "" }, changedelete = { text = "▎" }, untracked = { text = "▎" } } } },
  { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate", event = { "BufReadPost", "BufNewFile" }, opts = { ensure_installed = { "bash", "c", "css", "html", "javascript", "json", "lua", "markdown", "markdown_inline", "python", "ruby", "rust", "toml", "tsx", "typescript", "vim", "vimdoc", "yaml" }, auto_install = true, highlight = { enable = true }, indent = { enable = true } }, },
  { "neovim/nvim-lspconfig", event = { "BufReadPre", "BufNewFile" } },
  { "hrsh7th/nvim-cmp", event = "InsertEnter", dependencies = { "hrsh7th/cmp-nvim-lsp", "hrsh7th/cmp-buffer", "hrsh7th/cmp-path" } },
  { "Exafunction/codeium.nvim", event = "InsertEnter", dependencies = { "hrsh7th/nvim-cmp" } },
  { "stevearc/conform.nvim", event = { "BufReadPre", "BufNewFile" }, opts = { formatters_by_ft = { lua = { "stylua" }, python = { "black", "isort" }, javascript = { "prettierd", "prettier" }, typescript = { "prettierd", "prettier" }, json = { "prettierd", "prettier" }, yaml = { "prettierd", "prettier" }, markdown = { "prettierd", "prettier" }, rust = { "rustfmt" } }, format_on_save = { timeout_ms = 500 } } },
  { "numToStr/Comment.nvim", keys = { { "gcc", mode = { "n", "v" }, desc = "Comment" }, { "gc", mode = { "n", "v" }, desc = "Block comment" } } },
  { "akinsho/bufferline.nvim", event = "VeryLazy", dependencies = "nvim-tree/nvim-web-devicons", opts = { options = { mode = "buffers", diagnostics = "nvim_lsp", buffer_close_icon = "", separator_style = "thin" } }, keys = { { "[b", "<cmd>BufferLineCyclePrev<cr>" }, { "]b", "<cmd>BufferLineCycleNext<cr>" }, { "<leader>bd", "<cmd>bdelete<cr>" } } },
  { "nvim-lualine/lualine.nvim", event = "VeryLazy", opts = { options = { theme = "tokyonight", globalstatus = true } } },
  { "folke/which-key.nvim", event = "VeryLazy" },
  { "j-hui/fidget.nvim", event = "LspAttach", opts = {} },
  { "folke/trouble.nvim", dependencies = "nvim-tree/nvim-web-devicons", cmd = { "Trouble", "TroubleToggle" }, keys = { { "<leader>xx", "<cmd>Trouble<cr>" }, { "<leader>xw", "<cmd>Trouble workspace_diagnostics<cr>" }, { "gR", "<cmd>Trouble lsp_references<cr>" } } },
  { "andymass/vim-matchup", event = "BufReadPost" },
  { "norcalli/nvim-colorizer.lua", event = { "BufReadPre", "BufNewFile" }, config = function() require("colorizer").setup({ css = { ft = "css" }, html = { ft = "html" }, tailwind = { ft = "css" } }) end },
  { "machakann/vim-highlightedyank", event = "BufRead", config = function() vim.g.highlightedyank_highlight_duration = 300 end },
  { "mrcjkb/rustaceanvim", version = "^4", ft = { "rust" } },
  { "mg979/vim-visual-multi", event = "BufEnter", config = function() vim.g.VM_default_options = { start_in_insert = false } end },
}, { defaults = { lazy = false }, performance = { rtp = { disabled_plugins = { "gzip", "tarPlugin", "tohtml", "tutor", "zipPlugin" } } } })
